insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Arivonimamo', 1);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Ryazanskaya', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Tvŭrditsa', 5);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Ţāmiyah', 3);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Abay', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Palama', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Karantaba', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Urzhar', 2);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Ormož', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Caçador', 5);
insert into restaurants (name, location, price_range) values ('KFC', 'Candating', 4);
insert into restaurants (name, location, price_range) values ('Dominos', 'Fonte da Vaca', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Vokhaïkó', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Cisitu', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Primorka', 1);
insert into restaurants (name, location, price_range) values ('KFC', 'Vilque Chico', 5);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Ḩalwān', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Nankou', 3);
insert into restaurants (name, location, price_range) values ('KFC', 'Trollhättan', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Sarilhos Grandes', 3);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Cikuda', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Trasak', 1);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Meixi', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'Paço', 3);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Outokumpu', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Cukalat', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Asyūţ', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Baisha', 5);
insert into restaurants (name, location, price_range) values ('KFC', 'Narawayong', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Kafr ash Shaykh', 3);
insert into restaurants (name, location, price_range) values ('Dominos', 'Dongxin', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Orda', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Daohe', 1);
insert into restaurants (name, location, price_range) values ('KFC', 'Šmarje pri Jelšah', 2);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Nanjin', 3);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Boussé', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'Brest', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Krajan Satu', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Unidad', 4);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Kentongan', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Kugluktuk', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'Driefontein', 5);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Quimistán', 2);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Aş Şūrah aş Şaghīrah', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Ngelak', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Lidian', 5);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Curuzú Cuatiá', 5);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Rio Grande da Serra', 4);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Vardablur', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Gaïtánion', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Las Junturas', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Bunol', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Tajur', 3);
insert into restaurants (name, location, price_range) values ('KFC', 'Shiling', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Pordapor Barat', 3);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Aricagua', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Tečovice', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Songnim', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Handa', 5);
insert into restaurants (name, location, price_range) values ('Mixue', 'Fuhe', 4);
insert into restaurants (name, location, price_range) values ('KFC', 'Hengshan', 5);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Gornji Milanovac', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Alis', 4);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Rockford', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'Zhangye', 1);
insert into restaurants (name, location, price_range) values ('KFC', 'Chartres', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Las Vegas', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Camino Real', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Kashima', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Koímisi', 3);
insert into restaurants (name, location, price_range) values ('KFC', 'Cipadung Timur', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Bojong', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Pasarkuok', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'Al Ḩīlah', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Starotitarovskaya', 3);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Stanovoye', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Padasono', 3);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Alannay', 1);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Yangtan', 2);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Dzięgielów', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Shcherbinka', 5);
insert into restaurants (name, location, price_range) values ('Dominos', 'Longbo', 4);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Casal', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Batroûn', 2);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Tisma', 3);
insert into restaurants (name, location, price_range) values ('Dominos', 'Fosses', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Ploso', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Xiaoyangqi', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Noeltoko', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Pulong Sampalok', 3);
insert into restaurants (name, location, price_range) values ('KFC', 'Krzyżanowice', 1);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Tytuvėnėliai', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Tayug', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'Al Fākhūrah', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Shiye', 1);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Riihimäki', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Kaburon', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Clodomira', 4);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Mizque', 5);
insert into restaurants (name, location, price_range) values ('Mixue', 'Jammāl', 2);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Brgy. Nalook, kalibo', 4);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Mesopotamía', 2);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Grimshaw', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Moriya', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Shanghuang', 2);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Chendong', 1);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Melekeok Village', 3);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Selaparang Timur', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Vigo', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Granja', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Yushu', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Samashki', 3);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Fulin', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Tafí del Valle', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'Jianchang', 4);
insert into restaurants (name, location, price_range) values ('KFC', 'Akzhal', 3);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Banyubang', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Beibao', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Mikhaylovsk', 4);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Poligny', 2);
insert into restaurants (name, location, price_range) values ('KFC', 'Drochia', 3);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Yläne', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Garagoa', 5);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Werota', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Maddela', 2);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Sacapulas', 4);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Gemena', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Xinqiao', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Al Mijlad', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Vitória da Conquista', 3);
insert into restaurants (name, location, price_range) values ('Mixue', 'Anyu', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Cibeuti', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'Dushang', 3);
insert into restaurants (name, location, price_range) values ('KFC', 'Vila Verde', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Boyang', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Kameda-honchō', 4);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Ningmute', 1);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Binjiang', 3);
insert into restaurants (name, location, price_range) values ('Mixue', 'Ngunguru', 5);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Khadan Khāk', 1);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Wuyanquan', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Majan', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'Pandanwangi', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Taizhou', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Kozova', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Longzui', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Shuangpu', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Jince', 5);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Roczyny', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Albertville', 4);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Rio das Ostras', 3);
insert into restaurants (name, location, price_range) values ('Dominos', 'Tevriz', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Espinal', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Saint Croix', 1);
insert into restaurants (name, location, price_range) values ('KFC', 'Abuxarda', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Turenki', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Buenos Aires', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'Doropeti', 1);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Baibu', 5);
insert into restaurants (name, location, price_range) values ('Dominos', 'Kuala Lumpur', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Piura', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Angoulême', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Providencia', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Tamanan', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Georgiyevka', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Hongshanzui', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Krasnyy Profintern', 3);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Xiaochengzi', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Lanat', 2);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Songgui', 3);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Mabay', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Gbarnga', 5);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Opatów', 1);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Kobryn', 5);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Fenglai', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Volodarsk', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Quinarayan', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Yaypan', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Sérifos', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Boavista', 3);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Luwan', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Mairinque', 5);
insert into restaurants (name, location, price_range) values ('KFC', 'Ngawen', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Arroyo Naranjo', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Zongga', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Algeciras', 1);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Dishnā', 3);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Mafraq', 5);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Cibalieur', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Arhust', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Tiyuguan', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Nassau', 4);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'San Pablo', 4);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Caetité', 4);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Bashtanka', 2);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Padangbatung', 2);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Usu', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Mahīn', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Kvasice', 5);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Nguigmi', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Yangping', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Pomahuaca', 5);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Krasnogorskoye', 5);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Icononzo', 4);
insert into restaurants (name, location, price_range) values ('KFC', 'Chongjin', 2);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Essen', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Oslomej', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Mubi', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Jamao al Norte', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Paitan Este', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Cercal', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'Tawan tawan', 2);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Jeffrey’s Bay', 1);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Boulogne-sur-Mer', 2);
insert into restaurants (name, location, price_range) values ('KFC', 'Fort Wayne', 5);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Cipunglu', 5);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Shīeli', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Cortes', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Sison', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'San Nicolas', 5);
insert into restaurants (name, location, price_range) values ('KFC', 'Haninge', 3);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Nelson', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Paris 03', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Maisons-Alfort', 4);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Rzozów', 4);
insert into restaurants (name, location, price_range) values ('Dominos', 'Novi Karlovci', 3);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Tríkala', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Revelstoke', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Severnyy', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Selopuro', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Bhunya', 1);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Qā’en', 5);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Keboncau', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Kaesŏng', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Kigoma', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'Waihai', 1);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Wadeng', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'San Miguel', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Xinyang', 3);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Kanal', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Shujāābād', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'María la Baja', 4);
insert into restaurants (name, location, price_range) values ('KFC', 'Wattala', 5);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Faranah', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Yuetang', 3);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Hujia', 2);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Santa Ana', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Quận Phú Nhuận', 2);
insert into restaurants (name, location, price_range) values ('KFC', 'Pedome', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Dolní Studénky', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Vårby', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Lanxi', 4);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Cortiços', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Yubileyny', 1);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Ludvika', 1);
insert into restaurants (name, location, price_range) values ('KFC', 'Uppsala', 5);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Encañada', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Poręba Spytkowska', 5);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Suna', 4);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Boljoon', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Artsvanist', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Aldergrove', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Karangtawar', 3);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Yuexi', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'La Huerta', 2);
insert into restaurants (name, location, price_range) values ('KFC', 'Nikel’', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Bājitpur', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Bettendorf', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Phonphisai', 5);
insert into restaurants (name, location, price_range) values ('Mixue', 'Xubu', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Agrelo', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'Kopen', 4);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Paôy Pêt', 3);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Banjar Laing', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Yuanyang', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Yangzi', 3);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Chelopech', 4);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Dawangzhuang', 1);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Lere', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Strumica', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Tarakan', 3);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Camingawan', 2);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Zhangjiayuan', 3);
insert into restaurants (name, location, price_range) values ('Mixue', 'Az Zarbah', 5);
insert into restaurants (name, location, price_range) values ('Dominos', 'Habana del Este', 4);
insert into restaurants (name, location, price_range) values ('Dominos', 'Skulsk', 2);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Jianxin', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Lezhu', 1);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Zubin Potok', 3);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Regla', 1);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Segovia', 2);
insert into restaurants (name, location, price_range) values ('KFC', 'Khān Arnabah', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Cibinong Satu', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Oslo', 3);
insert into restaurants (name, location, price_range) values ('Mixue', 'Binangun', 2);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Qozonketkan', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Orange Farm', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Yazman', 1);
insert into restaurants (name, location, price_range) values ('Pizza Palace', '‘Afrīn', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Bagong Pagasa', 1);
insert into restaurants (name, location, price_range) values ('KFC', 'Poço Verde', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Medveđa', 2);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Phra Nakhon Si Ayutthaya', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Stockholm', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Sampaloc', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Lintingkou', 2);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Ludza', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Beira', 3);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Lailunggi', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'København', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Araouane', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Şūrān', 3);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Sykiés', 3);
insert into restaurants (name, location, price_range) values ('KFC', 'Huaping', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Limbaži', 2);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Lecheng', 4);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Taraz', 4);
insert into restaurants (name, location, price_range) values ('KFC', 'Caqu', 4);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Pare', 1);
insert into restaurants (name, location, price_range) values ('KFC', 'Kabīrwāla', 3);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Botoh', 1);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Saukkola', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Černá Hora', 4);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Skore', 5);
insert into restaurants (name, location, price_range) values ('Dominos', 'Mendoza', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Luoshe', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Chengxi', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Kaleybar', 5);
insert into restaurants (name, location, price_range) values ('Dominos', 'Kankan', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Marco', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Xipingle', 2);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Istres', 2);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Castelo', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Krandil', 5);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Łapsze Niżne', 2);
insert into restaurants (name, location, price_range) values ('KFC', 'Hanlin', 4);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Bulgan', 5);
insert into restaurants (name, location, price_range) values ('Dominos', 'Dishnā', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Galamares', 4);
insert into restaurants (name, location, price_range) values ('Dominos', 'Chelyabinsk', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Meilisi', 4);
insert into restaurants (name, location, price_range) values ('KFC', 'Itapevi', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Mazeikiai', 4);
insert into restaurants (name, location, price_range) values ('KFC', 'Valencia', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Solna', 4);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Badajoz', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Wulan Haye', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Ngulangan', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Xianxiang', 4);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'San Juan', 4);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Huangzhan', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Patarrá', 3);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Charlotte', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Panyingkiran', 5);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Mascouche', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'Bothaville', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Nicoya', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'Palopat', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Oslo', 4);
insert into restaurants (name, location, price_range) values ('KFC', 'Biên Hòa', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Podsineye', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Villa Dolores', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Sacanta', 1);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Palmdale', 5);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Siruma', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Maha Sarakham', 2);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Kafr ad Dīk', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Srinagarindra', 4);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Muhur', 4);
insert into restaurants (name, location, price_range) values ('Dominos', '‘Ayn al Bayḑā', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Sabinópolis', 1);
insert into restaurants (name, location, price_range) values ('KFC', 'San Miguel', 5);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Loivos', 1);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Vlasenica', 5);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Bzenec', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Hengjie', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Xinghai', 3);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Kuching', 2);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Novaya Usman’', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Pýli', 5);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Lokatadho', 4);
insert into restaurants (name, location, price_range) values ('KFC', 'Wakduwa’ Barat', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Nong Bua Daeng', 2);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Pasadena', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Lianrao', 2);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Isakly', 4);
insert into restaurants (name, location, price_range) values ('Dominos', 'Dolní Studénky', 2);
insert into restaurants (name, location, price_range) values ('KFC', 'Shuangqiao', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Orda', 1);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Cúa', 3);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Lota', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Cheb', 4);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Rusocice', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Princeton', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Bolnisi', 3);
insert into restaurants (name, location, price_range) values ('KFC', 'Angeghakot’', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Javorník', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'San Isidro', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Caxias', 1);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Yorosso', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Nagareyama', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Knin', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Szczerbice', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Sankera', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Yolöten', 2);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Grzęska', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Tukan', 4);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Prior Velho', 3);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Kramsk', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'La Falda', 2);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Iúna', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Sulitair', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Diawara', 4);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Krasna', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Strasbourg', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Memphis', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Borgustanskaya', 3);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Jiuheyuan', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Yamazakichō-nakabirose', 2);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Tanggulangin', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'San Remigio', 5);
insert into restaurants (name, location, price_range) values ('Dominos', 'Cikotok', 3);
insert into restaurants (name, location, price_range) values ('Mixue', 'Karanganyar', 2);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Vlachovo Březí', 3);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Lyaskelya', 1);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Taoyuan', 3);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Mende', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Al Manşūrah', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Lebedyn', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Villavicencio', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Dok Kham Tai', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Cincinnati', 2);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Nunbaundelha', 3);
insert into restaurants (name, location, price_range) values ('Mixue', 'Shigu', 5);
insert into restaurants (name, location, price_range) values ('Mixue', 'Xianghu', 3);
insert into restaurants (name, location, price_range) values ('Pizza Palace', '‘Afak', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Bousso', 3);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Chornukhy', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Yaoundé', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Luleå', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Oof', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Gavinhos de Baixo', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Tourcoing', 4);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Pesagen', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Léo', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Manicahan', 3);
insert into restaurants (name, location, price_range) values ('Dominos', 'Meaux', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Bumba', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'El Tejocote', 4);
insert into restaurants (name, location, price_range) values ('KFC', 'Jardin', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Zaghouan', 2);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Xintang', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Bago City', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Dębowiec', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'Wanfang', 5);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Yaozhuang', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Norcasia', 3);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Yuhuang', 1);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Jingyang', 2);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Hengshan', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Kende', 2);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Duszniki-Zdrój', 4);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Brześć Kujawski', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Banovo Polje', 1);
insert into restaurants (name, location, price_range) values ('KFC', 'Chengmagang', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Cabaritan East', 4);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Shuibian', 3);
insert into restaurants (name, location, price_range) values ('Mixue', 'Lamego', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'Ballitoville', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Zgornje Bitnje', 4);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Pasadena', 3);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Valledupar', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Kisangani', 5);
insert into restaurants (name, location, price_range) values ('Dominos', 'Brwinów', 3);
insert into restaurants (name, location, price_range) values ('Mixue', 'Maisons-Alfort', 2);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Bassa', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Lincoln', 1);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Alma', 3);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Hecheng', 4);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Helsingborg', 1);
insert into restaurants (name, location, price_range) values ('KFC', 'Zhuangbu', 1);
insert into restaurants (name, location, price_range) values ('KFC', 'Prioso Barat', 4);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Cikou', 5);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Khoronk’', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Rukungiri', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Anda', 3);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Semampirbarat', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Ambat', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Minneapolis', 5);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Gostilitsy', 4);
insert into restaurants (name, location, price_range) values ('Dominos', 'Huaqiu', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Tangga', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Don Mueang', 3);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Fastiv', 5);
insert into restaurants (name, location, price_range) values ('Dominos', 'Yuankeng', 5);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Tver', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Cirateun', 2);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Houmt Souk', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Garisul', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Templeogue', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Kousséri', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Fernando Gutierrez Barrios', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Benito Juarez', 2);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Niugan', 5);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Kaédi', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Hidalgo', 5);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Panenjoan', 3);
insert into restaurants (name, location, price_range) values ('Mixue', 'Dulangan', 4);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Finspång', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Gongfang', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'Niquelândia', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Staroderevyankovskaya', 4);
insert into restaurants (name, location, price_range) values ('KFC', 'El Hatillo', 3);
insert into restaurants (name, location, price_range) values ('KFC', 'Buenos Aires', 1);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Nova Viçosa', 1);
insert into restaurants (name, location, price_range) values ('KFC', 'Rotunda', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Trondheim', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Dalheim', 4);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Horodyshche', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Planken', 4);
insert into restaurants (name, location, price_range) values ('Dominos', 'Emmen', 5);
insert into restaurants (name, location, price_range) values ('Mixue', 'Bardo', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Krokeaí', 4);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Cawayan', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'Culeng', 1);
insert into restaurants (name, location, price_range) values ('KFC', 'Anibare', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Godziszów Pierwszy', 4);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Hengli', 2);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Sekarjalak', 1);
insert into restaurants (name, location, price_range) values ('KFC', 'Villa del Rosario', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Primorsko', 2);
insert into restaurants (name, location, price_range) values ('KFC', 'Calvário', 4);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Guadalupe', 3);
insert into restaurants (name, location, price_range) values ('Mixue', 'Manorom', 5);
insert into restaurants (name, location, price_range) values ('US Pizza', 'New York City', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Bay Roberts', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Dashiqiao', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Kapenguria', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Gangmei', 3);
insert into restaurants (name, location, price_range) values ('KFC', 'East End', 1);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Utrecht (stad)', 3);
insert into restaurants (name, location, price_range) values ('Dominos', 'Novo', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Cidade Velha', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Tuchów', 4);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Zhuting', 4);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Eg', 2);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Fengzhou', 4);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Manadas', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'San Remigio', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Mandaluyong City', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Puyang', 1);
insert into restaurants (name, location, price_range) values ('KFC', 'Pokhara', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Legen', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Alvito de São Pedro', 5);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Kostyantynivka', 2);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Dongyuan', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Färgelanda', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Batang', 3);
insert into restaurants (name, location, price_range) values ('Mixue', 'Gala', 5);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Neftobod', 5);
insert into restaurants (name, location, price_range) values ('Dominos', 'Xiahong', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Bangunharja', 2);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Quma', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Tegalagung', 5);
insert into restaurants (name, location, price_range) values ('Mixue', 'Laironja', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Seogeom-ri', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Juru', 1);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Oelaba', 2);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Nyrkiv', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Lagoa de Albufeira', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Novoselë', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Xiaojiang', 1);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Krahës', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Bantogon', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Glubokiy', 5);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Qiaoshi', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Tohautu', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Piteå', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Malusac', 5);
insert into restaurants (name, location, price_range) values ('Mixue', 'Moita', 2);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Vrangel’', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'La Gacilly', 2);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Asaita', 4);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Hangchuan', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'Manika', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Dianfang', 5);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Mafraq', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Klenak', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Labuhan', 4);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Áthyra', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Marseille', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Xinjie', 1);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Shibushi', 2);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Taiyuan', 5);
insert into restaurants (name, location, price_range) values ('Mixue', 'Oinófyta', 4);
insert into restaurants (name, location, price_range) values ('KFC', 'Štěchovice', 3);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Yangzhuang', 4);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Güiria', 1);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Amphoe Sikhiu', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Dzerzhinsk', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Yonezawa', 1);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Xinxing', 4);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Chonghe', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Fuhe', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Baima', 2);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Strathmore', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Washington', 3);
insert into restaurants (name, location, price_range) values ('Mixue', 'Polonnaruwa', 4);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Hāgere Hiywet', 3);
insert into restaurants (name, location, price_range) values ('Mixue', 'Shuicha', 4);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Sankeyushu', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Fougamou', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Lopez Jaena', 4);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Tangzha', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Gominhães', 5);
insert into restaurants (name, location, price_range) values ('KFC', 'Mölndal', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Yuqi', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Cabak Satu', 4);
insert into restaurants (name, location, price_range) values ('Dominos', 'Xigebi', 3);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Awilega', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Sobinka', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Ryazanskiy', 4);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Rejoyoso', 5);
insert into restaurants (name, location, price_range) values ('KFC', 'Limbaži', 5);
insert into restaurants (name, location, price_range) values ('Mixue', 'Ushuaia', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Cantaura', 5);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Baki', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'Zhen’an', 3);
insert into restaurants (name, location, price_range) values ('KFC', 'Kallífytos', 1);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Ziębice', 3);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Czerwonak', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Loma Bonita', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Bombu', 5);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Biaoxi', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Călăraşi', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'Ponta Porã', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'New Glasgow', 5);
insert into restaurants (name, location, price_range) values ('Dominos', 'Lucija', 5);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Évry', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Cértegui', 5);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Enonkoski', 4);
insert into restaurants (name, location, price_range) values ('Dominos', 'El Perico', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'Fonte da Vaca', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Bajo Pichanaqui', 4);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Ciela Lebak', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Horodok', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Roshchino', 4);
insert into restaurants (name, location, price_range) values ('KFC', 'San Bartolomé Milpas Altas', 4);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Akankpa', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Torres Novas', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Igreja', 4);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Cikarang', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Polovinnoye', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Monte da Pedra', 1);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Anjirmuara', 2);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Länsi-Turunmaa', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Longtang', 4);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Huayuan', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Astara', 5);
insert into restaurants (name, location, price_range) values ('Dominos', 'Rochefort', 3);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Albergaria', 1);
insert into restaurants (name, location, price_range) values ('KFC', 'Cha-am', 5);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Cartagena', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Concepción Tutuapa', 5);
insert into restaurants (name, location, price_range) values ('Mixue', 'Gantang', 1);
insert into restaurants (name, location, price_range) values ('US Pizza', 'San Fernando Apure', 5);
insert into restaurants (name, location, price_range) values ('Dominos', 'Heilbronn', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Benguela', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Dartang', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Kardzhin', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'At-Bashi', 3);
insert into restaurants (name, location, price_range) values ('Mixue', 'Jaša Tomić', 2);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Northern Suburbs Mc', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Santo Amaro', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Seiça', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Lichengdao', 2);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Ngrejo', 5);
insert into restaurants (name, location, price_range) values ('KFC', 'Pingzhuang', 4);
insert into restaurants (name, location, price_range) values ('Dominos', 'Muonio', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Huité', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'Jiezi', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Sydney', 3);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Zhuge', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Waiwejak', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Mira', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Yandun', 4);
insert into restaurants (name, location, price_range) values ('KFC', 'Tonghu', 5);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Maraial', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Tianbao', 2);
insert into restaurants (name, location, price_range) values ('KFC', 'Bantul', 5);
insert into restaurants (name, location, price_range) values ('Mixue', 'Smolyaninovo', 1);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Mahaica Village', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Daja Lorong', 5);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Concórdia', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Pereleshino', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Nuevitas', 4);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Jinotega', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Moroni', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'El Real', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Rokoy', 4);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Tambopata', 1);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Polazna', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Karanggedang', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'Dahe', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Touho', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Zalishchyky', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Granada', 5);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Ciawi', 2);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Shijiao', 4);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Temorlorong', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Xiaolong', 3);
insert into restaurants (name, location, price_range) values ('KFC', 'Gouqi', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Särkisalo', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Knyaze-Volkonskoye', 5);
insert into restaurants (name, location, price_range) values ('KFC', 'Gumdag', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'El Perico', 5);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Plumtree', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Bambang', 3);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Aksha', 1);
insert into restaurants (name, location, price_range) values ('KFC', 'Baranów', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Alavus', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'Nepomuceno', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Liangshan', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Lipin Bor', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Jiangshi', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Pondokdalem', 3);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Vojkovice', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Tam Bình', 1);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Sułoszowa', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Tazarine', 5);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Jermuk', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Turar Ryskulov', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Qianpai', 3);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Djibo', 5);
insert into restaurants (name, location, price_range) values ('Mixue', 'Nizhniy Tsasuchey', 3);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'El Paraiso', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Ljig', 5);
insert into restaurants (name, location, price_range) values ('Mixue', 'Muramatsu', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Doom', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Puerto Francisco de Orellana', 2);
insert into restaurants (name, location, price_range) values ('KFC', 'Kasserine', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Baturité', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Waeng Yai', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Tiyingtali Kelod', 1);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Tadine', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Bastia', 2);
insert into restaurants (name, location, price_range) values ('KFC', 'Mezinovskiy', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'Dadus', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Changzhi', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Feicheng', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'Pelileo', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Pingshan', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Plyussa', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Pawłowiczki', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Alverca do Ribatejo', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Tall Abyaḑ', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Višňova', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Steinkjer', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Dinititi', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Heshui', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Limoges', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Meiyuan', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Sanlei', 3);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'San José de los Remates', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Xikou', 4);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Nova Viçosa', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Taluncemara', 5);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Tiguion', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Affery', 1);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Mahābād', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Jeminay', 1);
insert into restaurants (name, location, price_range) values ('KFC', 'Banjar Banyualit', 1);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Pulau Pinang', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'Verrettes', 1);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Clichy', 1);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Tangkolo', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Vancouver', 5);
insert into restaurants (name, location, price_range) values ('Mixue', 'Lao Suea Kok', 1);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Sixi', 2);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Liaozhong', 3);
insert into restaurants (name, location, price_range) values ('Dominos', 'Kapsan-ŭp', 2);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Echarate', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Tampere', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Huiwen', 4);
insert into restaurants (name, location, price_range) values ('Dominos', 'Šentvid pri Stični', 4);
insert into restaurants (name, location, price_range) values ('KFC', 'Nizhneivkino', 4);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Kawm Ḩamādah', 2);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Dawung', 2);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Suyang', 2);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Djibouti', 1);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Kiraman', 4);
insert into restaurants (name, location, price_range) values ('Dominos', 'Lauro de Freitas', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Valeirinha', 3);
insert into restaurants (name, location, price_range) values ('Mixue', 'Tiwi', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Zákupy', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Algarvia', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Kuncen', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Banjar Kawan', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Pingtan', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'West Jerusalem', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Lesichevo', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'North Shore', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Oliveira', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'Bankeryd', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Adolfo Lopez Mateos', 5);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Schäffern', 4);
insert into restaurants (name, location, price_range) values ('Dominos', 'Bol’shoye Selo', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'Perreng', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Teutônia', 3);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Donghai', 5);
insert into restaurants (name, location, price_range) values ('KFC', 'Wuluo', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Luknovo', 1);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Daitōchō', 5);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Balneário Camboriú', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Bahía Blanca', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Zhangjiabao', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Tal’ne', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Pyshchug', 3);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Xihe', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Dolno Palčište', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Lukou', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Micoud', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Musanze', 2);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Toledo', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'Buzovna', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Tabinay', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Bang Lamung', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Luniao', 1);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Qarqīn', 5);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Niny', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Voždovac', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'Shijiao', 1);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Xinjiezhen', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Maripa', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Kertamukti', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Ust’-Kachka', 5);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Jiangyan', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Castro', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Fuchūchō', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Dongshui', 2);
insert into restaurants (name, location, price_range) values ('KFC', 'Korolevo', 1);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Tambo Grande', 4);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Mampong', 3);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Cikomara', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'El Banco', 3);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Ariquemes', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Plagiári', 2);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Yinji', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Káto Dhiminió', 4);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Auna', 2);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Padre Paraíso', 4);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Hafnarfjörður', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Guangyuan', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'La Jagua de Ibirico', 1);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Mazongshan', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Mapusagafou', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Pledo', 4);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Hendaye', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Skoura', 2);
insert into restaurants (name, location, price_range) values ('KFC', 'Daliuhao', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Houston', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Komarno', 2);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Kribi', 3);
insert into restaurants (name, location, price_range) values ('KFC', 'Rochester', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'El Mirador', 3);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Hallstavik', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Kalān Deh', 3);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Timbiras', 4);
insert into restaurants (name, location, price_range) values ('Dominos', 'Jetafe', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Okakarara', 4);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Resistencia', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Xinhua', 1);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'María la Baja', 4);
insert into restaurants (name, location, price_range) values ('KFC', 'Calçada', 4);
insert into restaurants (name, location, price_range) values ('KFC', 'Gislaved', 2);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Tianyi', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Castelsarrasin', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Khok Charoen', 5);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Alkmaar', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Jasper Park Lodge', 2);
insert into restaurants (name, location, price_range) values ('KFC', 'Borlänge', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Calaya', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Ibarra', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Ngaruawahia', 3);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Agat Village', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Bordeaux', 4);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Wongka', 1);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Miaoya', 1);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Bubullimë', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Cabangahan', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Camp Flora', 5);
insert into restaurants (name, location, price_range) values ('Dominos', 'Khlong Toei', 3);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Buk', 4);
insert into restaurants (name, location, price_range) values ('KFC', 'Shuangbaiyang', 5);
insert into restaurants (name, location, price_range) values ('Mixue', 'Banjar Bali', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'Wenquan', 4);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Pomar', 1);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Dioila', 1);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Bilalang', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'München', 5);
insert into restaurants (name, location, price_range) values ('Dominos', 'Parravak’ar', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Xuelu', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Vienna', 4);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Tamot', 3);
insert into restaurants (name, location, price_range) values ('Mixue', 'Layu', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Phichit', 3);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Vaggeryd', 5);
insert into restaurants (name, location, price_range) values ('Dominos', 'Huntsville', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Phoenix', 4);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Thị Trấn Quảng Uyên', 5);
insert into restaurants (name, location, price_range) values ('KFC', 'Kŭrdzhali', 2);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Daze', 4);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Tiwi', 4);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Baitu', 5);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Irecê', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Dengjiang', 4);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Zhongshan', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Langkapcaang Hilir', 2);
insert into restaurants (name, location, price_range) values ('Mixue', 'Bebedahan', 4);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Újezd', 4);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Chitré', 2);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Derviçian', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Litein', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Kuala Lumpur', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Sandaohezi', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Dacheng', 2);
insert into restaurants (name, location, price_range) values ('KFC', 'Tianchang', 4);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Gaza', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Lorino', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Jaciara', 4);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Chastyye', 5);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'New Shagunnu', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Radzanów', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Dobdoban', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'San Bautista', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Yacimiento Río Turbio', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Al Hadā', 2);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Santo Tomas', 1);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Kasiyan', 5);
insert into restaurants (name, location, price_range) values ('KFC', 'Hŭngju-dong', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'Vorzel’', 5);
insert into restaurants (name, location, price_range) values ('Dominos', 'Lameiro', 3);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Tajan', 5);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Meilin', 1);
insert into restaurants (name, location, price_range) values ('Mixue', 'Bratislava', 5);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Reguengos de Monsaraz', 2);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Prnjavor', 1);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Emar', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Pakisrejo', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Angra dos Reis', 1);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Asopós', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Klumbu', 3);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Catriel', 1);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Fatuulan', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Jaguariaíva', 4);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Jesenice', 3);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Folques', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Salekhard', 1);
insert into restaurants (name, location, price_range) values ('Dominos', 'Napalitan', 5);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Jadów', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Phunphin', 4);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Birobidzhan', 3);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Lian', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Huangbu', 5);
insert into restaurants (name, location, price_range) values ('Mixue', 'Cikijing', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Dangcalan', 1);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Hrtkovci', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Mikuni', 3);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Sukadana', 2);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Leuwayang', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Wojciechów', 1);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Gongnong', 1);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Slatina', 2);
insert into restaurants (name, location, price_range) values ('KFC', 'Amuñgan', 5);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Don Chedi', 2);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Fajã de Cima', 2);
insert into restaurants (name, location, price_range) values ('KFC', 'Luzhuangzi', 2);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Wantian', 3);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Nkpor', 1);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Mahdishahr', 5);
insert into restaurants (name, location, price_range) values ('Dominos', 'Iktābah', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Gizo', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'Karangbalong', 3);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Anápolis', 4);
insert into restaurants (name, location, price_range) values ('US Pizza', 'Tanushimarumachi-toyoki', 2);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Nashville', 1);
insert into restaurants (name, location, price_range) values ('The Hungry Panda', 'Luoqiao', 2);
insert into restaurants (name, location, price_range) values ('Pizza Palace', 'Kose', 2);
insert into restaurants (name, location, price_range) values ('Dominos', 'Naberera', 4);
insert into restaurants (name, location, price_range) values ('Dominos', 'Kratovo', 5);
insert into restaurants (name, location, price_range) values ('Tasty Tacos', 'Horten', 1);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Virje', 4);
insert into restaurants (name, location, price_range) values ('Mixue', 'Kafr Dān', 4);
insert into restaurants (name, location, price_range) values ('KFC', 'Banayoyo', 2);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Hamm', 3);
insert into restaurants (name, location, price_range) values ('Sizzle Grill', 'Daixi', 5);
insert into restaurants (name, location, price_range) values ('Cafe Bistro', 'Menzel Jemil', 3);
insert into restaurants (name, location, price_range) values ('McDonalds', 'Đắk Glei', 1);
insert into restaurants (name, location, price_range) values ('KFC', 'Peña Blanca', 2);
insert into restaurants (name, location, price_range) values ('Pizza Hut', 'Cabudare', 3);
